mod registry;
mod traits;

pub use registry::PluginRegistry;
pub use traits::{Plugin, PluginInfo};

pub mod admin;
pub mod adv;
pub mod afk;
pub mod callvote;
pub mod censor;
pub mod censorurt;
pub mod chatlogger;
pub mod countryfilter;
pub mod customcommands;
pub mod discord;
pub mod firstkill;
pub mod flagannounce;
pub mod follow;
pub mod geowelcome;
pub mod headshotcounter;
pub mod login;
pub mod makeroom;
pub mod mapconfig;
pub mod namechecker;
pub mod nickreg;
pub mod pingwatch;
pub mod poweradminurt;
pub mod scheduler;
pub mod spamcontrol;
pub mod spawnkill;
pub mod specchecker;
pub mod spree;
pub mod stats;
pub mod tk;
pub mod vpncheck;
pub mod welcome;
pub mod xlrstats;
