//! Dispatch table mapping `HubAction` values to concrete operations.

use serde_json::json;

use crate::config::HubSection;
use crate::sync::protocol::{HubAction, HubProgressEvent, MintClientCertRequest, MintClientCertResponse};

use super::{client_manager, game_server_manager};

/// Generate a short random hex password suitable for RCON / admin use.
/// 6 hex chars (3 bytes of entropy) — enough to avoid casual collisions
/// while staying easy to copy/paste from the UI.
fn random_pass() -> String {
    use rand::RngCore;
    let mut buf = [0u8; 3];
    rand::thread_rng().fill_bytes(&mut buf);
    format!("{:02x}{:02x}{:02x}", buf[0], buf[1], buf[2])
}

/// Try to discover the hub host's public IPv4 address by querying a small
/// set of well-known echo services. Returns `None` only if every probe
/// fails. Called when the admin leaves the "public IP" wizard field blank.
async fn detect_public_ip(http: &reqwest::Client) -> Option<String> {
    const PROBES: &[&str] = &[
        "https://api.ipify.org",
        "https://ifconfig.me/ip",
        "https://icanhazip.com",
        "https://ipv4.icanhazip.com",
        "https://checkip.amazonaws.com",
        "https://ident.me",
    ];
    for url in PROBES {
        match http
            .get(*url)
            .timeout(std::time::Duration::from_secs(5))
            .send()
            .await
        {
            Ok(resp) if resp.status().is_success() => {
                if let Ok(body) = resp.text().await {
                    let ip = body.trim();
                    // Reject anything that doesn't parse as an IPv4 addr or is RFC1918.
                    if let Ok(parsed) = ip.parse::<std::net::IpAddr>() {
                        if is_public_addr(&parsed) {
                            tracing::info!(url = %url, ip = %ip, "Detected hub public IP");
                            return Some(ip.to_string());
                        } else {
                            tracing::debug!(url = %url, ip = %ip, "Probe returned non-public IP, skipping");
                        }
                    }
                }
            }
            Ok(resp) => {
                tracing::debug!(url = %url, status = %resp.status(), "Public IP probe non-2xx");
            }
            Err(e) => {
                tracing::debug!(url = %url, error = %e, "Public IP probe failed");
            }
        }
    }
    None
}

/// True if `addr` is a globally-routable public address (not loopback,
/// link-local, unspecified, or in an RFC1918 private block).
fn is_public_addr(addr: &std::net::IpAddr) -> bool {
    if addr.is_loopback() || addr.is_unspecified() || addr.is_multicast() {
        return false;
    }
    match addr {
        std::net::IpAddr::V4(v4) => {
            if v4.is_private() || v4.is_link_local() || v4.is_broadcast() {
                return false;
            }
            // 100.64.0.0/10 — CGNAT
            let o = v4.octets();
            if o[0] == 100 && (o[1] & 0xC0) == 64 {
                return false;
            }
            true
        }
        std::net::IpAddr::V6(v6) => {
            // Conservative: reject unique local (fc00::/7) and link-local (fe80::/10).
            let seg = v6.segments()[0];
            if (seg & 0xFE00) == 0xFC00 {
                return false;
            }
            if (seg & 0xFFC0) == 0xFE80 {
                return false;
            }
            true
        }
    }
}

/// Helper that posts a single progress event to the master. Failure is
/// logged and swallowed — progress reporting is best-effort and must
/// never cause the owning action to fail.
async fn report_progress(
    http: &reqwest::Client,
    base_url: &str,
    action_id: &str,
    seq: u32,
    step: &str,
    message: &str,
    percent: Option<u8>,
) {
    let event = HubProgressEvent {
        action_id: action_id.to_string(),
        seq,
        step: step.to_string(),
        message: message.to_string(),
        percent,
        ts: chrono::Utc::now(),
    };
    if let Err(e) = http
        .post(format!("{}/internal/hub/progress", base_url))
        .json(&event)
        .send()
        .await
    {
        tracing::debug!(action_id = %action_id, error = %e, "Failed to post progress event");
    }
}

/// Build an `r3.toml` for a hub-managed client. Mirrors the layout the
/// standalone installer writes in `generate_client_config`, minus any
/// fields that are configured later by the master web UI wizard.
fn render_client_toml(
    slug: &str,
    server_name: &str,
    master_sync_url: &str,
    client_dir: &std::path::Path,
) -> String {
    let certs_dir = client_dir.join("certs");
    format!(
        r#"# Rusty Rules Referee — Hub-managed client ({slug})
# Generated by hub on client install. Managed by master at {master}

[referee]
bot_name = "{server_name}"
bot_prefix = "^2R3:^3"
database = "sqlite://r3.db"
logfile = "r3.log"
log_level = "info"

[server]
public_ip = "0.0.0.0"
port = 0
rcon_password = ""
game_log = ""
delay = 0.33

[web]
enabled = false
bind_address = "0.0.0.0"
port = 2727
jwt_secret = ""

[update]
enabled = false
url = "https://r3.pugbot.net/api/updates"
channel = "beta"
check_interval = 3600
auto_restart = true

[client]
master_url = "{master}"
server_name = "{server_name}"
tls_cert = "{cert}"
tls_key = "{key}"
ca_cert = "{ca}"
sync_interval = 30
heartbeat_interval = 15

[[plugins]]
name = "admin"
enabled = true

[[plugins]]
name = "poweradminurt"
enabled = true

[[plugins]]
name = "censor"
enabled = true

[[plugins]]
name = "welcome"
enabled = true

[[plugins]]
name = "stats"
enabled = true
"#,
        slug = slug,
        server_name = server_name,
        master = master_sync_url,
        cert = certs_dir.join("client.crt").display(),
        key = certs_dir.join("client.key").display(),
        ca = certs_dir.join("ca.crt").display(),
    )
}

/// Execute a single hub action. Returns `(message, optional structured data)`.
pub async fn execute(
    http: &reqwest::Client,
    base_url: &str,
    hub_id: i64,
    hub_cfg: &HubSection,
    action_id: &str,
    action: HubAction,
) -> anyhow::Result<(String, Option<serde_json::Value>)> {
    match action {
        HubAction::InstallClient {
            slug,
            server_name,
            game_server,
            register_systemd: _,
        } => {
            // Normalize and fill in game-server params so the rest of the
            // install flow has a single source of truth (passwords, IP,
            // log paths) without sprinkling defaults at every call site.
            // Generating here means admins never see the "Configuration
            // Required" panel after a hub install, even if the UI forgot
            // to send a password or an IP couldn't be detected.
            let game_server = if let Some(mut params) = game_server {
                if params.rcon_password.trim().is_empty() {
                    params.rcon_password = random_pass();
                    tracing::info!(
                        %slug,
                        "Hub auto-generated RCON password for new game server"
                    );
                }
                if params
                    .admin_password
                    .as_deref()
                    .map(|s| s.trim().is_empty())
                    .unwrap_or(true)
                {
                    params.admin_password = Some(random_pass());
                    tracing::info!(
                        %slug,
                        "Hub auto-generated admin/referee password for new game server"
                    );
                }
                if params.public_ip.trim().is_empty() || params.public_ip.trim() == "0.0.0.0" {
                    if let Some(ip) = detect_public_ip(http).await {
                        params.public_ip = ip;
                    }
                    // If detection failed, leave it blank here — the mint
                    // block below will fall back to the hub's registered
                    // address or 127.0.0.1 so config_json still seeds.
                }
                Some(params)
            } else {
                None
            };

            report_progress(
                http,
                base_url,
                action_id,
                1,
                "mint_cert",
                &format!("Requesting client certificate for '{}'", slug),
                Some(10),
            )
            .await;
            // 1) Mint a client certificate + register the GameServer row
            //    on the master via the hub's mTLS-authenticated endpoint.
            //    When the wizard included game_server params, also pass
            //    the RCON + file paths through so the master seeds
            //    `config_json` and the new server shows up pre-configured
            //    in the UI instead of the "Configuration Required" panel.
            let (address, port, rcon_password, game_log, server_cfg_path) =
                if let Some(params) = &game_server {
                    // Public IP was already resolved above (admin-supplied
                    // → detect_public_ip). If still blank the master will
                    // fall back to the hub's registered address, but we
                    // must NOT bind a LAN/loopback address here — the UrT
                    // dedicated server announces itself on this value and
                    // players connect directly to it.
                    let addr = if params.public_ip.trim().is_empty()
                        || params.public_ip.trim() == "0.0.0.0"
                    {
                        String::new()
                    } else {
                        params.public_ip.trim().to_string()
                    };
                    // Install path is deterministic: <urt_install_root>/<slug>/q3ut4.
                    // Canonicalize so config_json has absolute paths (the log
                    // tailer + cfg editor on the client need absolute paths).
                    let inst = game_server_manager::install_path(hub_cfg, &slug);
                    let abs = inst.canonicalize().unwrap_or(inst);
                    let q3ut4 = abs.join("q3ut4");
                    (
                        addr,
                        params.port,
                        Some(params.rcon_password.clone()),
                        Some(q3ut4.join("games.log").to_string_lossy().to_string()),
                        Some(q3ut4.join("server.cfg").to_string_lossy().to_string()),
                    )
                } else {
                    (String::new(), 0u16, None, None, None)
                };
            let mint_req = MintClientCertRequest {
                hub_id,
                slug: slug.clone(),
                server_name: server_name.clone(),
                address,
                port,
                rcon_password,
                game_log,
                server_cfg_path,
            };
            let resp = http
                .post(format!("{}/internal/hub/mint-client-cert", base_url))
                .json(&mint_req)
                .send()
                .await
                .map_err(|e| anyhow::anyhow!("mint-client-cert request: {}", e))?;
            if !resp.status().is_success() {
                let status = resp.status();
                let body = resp.text().await.unwrap_or_default();
                anyhow::bail!("mint-client-cert returned {}: {}", status, body);
            }
            let mint: MintClientCertResponse = resp
                .json()
                .await
                .map_err(|e| anyhow::anyhow!("parse mint-client-cert response: {}", e))?;

            report_progress(
                http,
                base_url,
                action_id,
                2,
                "install_client",
                "Writing client config, certificates and systemd unit",
                Some(40),
            )
            .await;

            // 2) Render r3.toml and write certs + install systemd drop-in.
            let dir = client_manager::client_dir(hub_cfg, &slug);
            let r3_toml = render_client_toml(&slug, &server_name, &mint.master_sync_url, &dir);
            client_manager::install_client(
                hub_cfg,
                &slug,
                &r3_toml,
                &mint.ca_cert,
                &mint.client_cert,
                &mint.client_key,
            )
            .await?;

            // 3) Optionally drop game-server files alongside the client.
            let mut data = json!({
                "slug": slug,
                "server_id": mint.server_id,
                "client_dir": dir.display().to_string(),
            });
            if let Some(params) = game_server {
                report_progress(
                    http,
                    base_url,
                    action_id,
                    3,
                    "install_game_server",
                    "Installing Urban Terror game server files",
                    Some(70),
                )
                .await;
                let path =
                    game_server_manager::install_game_server(hub_cfg, &slug, &params).await?;
                data["game_server_path"] = json!(path.display().to_string());

                // Seed the sub-client's install-state marker so the
                // master UI's Start/Stop/Restart actions (which the
                // client bot serves out of this file) recognise the
                // hub-managed game server as configured. Without this
                // the sub-client replies with "No configured game
                // server on this client — run the install wizard
                // first" even though everything else is in place.
                let abs_install = path.canonicalize().unwrap_or_else(|_| path.clone());
                let q3ut4 = abs_install.join("q3ut4");
                let state = crate::sync::protocol::UrtInstallState {
                    slug: slug.clone(),
                    files_present: true,
                    install_path: Some(abs_install.to_string_lossy().to_string()),
                    configured: true,
                    service_name: if params.register_systemd {
                        Some(format!("urt@{}.service", slug))
                    } else {
                        None
                    },
                    port: Some(params.port),
                    server_cfg_path: Some(q3ut4.join("server.cfg").to_string_lossy().to_string()),
                    game_log: Some(q3ut4.join("games.log").to_string_lossy().to_string()),
                };
                let state_file = dir.join("state").join("urt-install.json");
                if let Some(parent) = state_file.parent() {
                    if let Err(e) = std::fs::create_dir_all(parent) {
                        tracing::warn!(error = %e, path = %parent.display(),
                            "Failed to create state dir for sub-client install marker");
                    }
                }
                match serde_json::to_string_pretty(&state) {
                    Ok(json_text) => {
                        if let Err(e) = std::fs::write(&state_file, &json_text) {
                            tracing::warn!(error = %e, path = %state_file.display(),
                                "Failed to write urt-install.json for hub-managed client");
                        } else {
                            tracing::info!(
                                %slug,
                                path = %state_file.display(),
                                "Wrote sub-client install-state marker"
                            );
                            #[cfg(unix)]
                            {
                                use std::os::unix::fs::PermissionsExt;
                                let _ = std::fs::set_permissions(
                                    &state_file,
                                    std::fs::Permissions::from_mode(0o600),
                                );
                            }
                        }
                    }
                    Err(e) => tracing::warn!(error = %e,
                        "Failed to serialize UrtInstallState for hub-managed client"),
                }
            }

            report_progress(
                http,
                base_url,
                action_id,
                4,
                "done",
                &format!("Client '{}' installed", slug),
                Some(100),
            )
            .await;

            Ok((
                format!(
                    "Client '{}' installed (server_id={}, dir={})",
                    slug,
                    mint.server_id,
                    dir.display()
                ),
                Some(data),
            ))
        }
        HubAction::UninstallClient { slug, remove_data } => {
            report_progress(
                http,
                base_url,
                action_id,
                1,
                "uninstall_client",
                &format!("Disabling and removing client '{}'", slug),
                Some(20),
            )
            .await;
            let client_steps =
                client_manager::uninstall_client(hub_cfg, &slug, remove_data).await?;

            // Always cascade to game-server teardown: a hub-managed client
            // has a paired `urt@<slug>` unit and an install dir under
            // `urt_install_root/<slug>`. Leaving those behind is what the
            // admin is typically asking us to avoid.
            report_progress(
                http,
                base_url,
                action_id,
                2,
                "remove_game_server",
                &format!("Removing UrT game server files for '{}'", slug),
                Some(70),
            )
            .await;
            let gs_steps = game_server_manager::remove_game_server(hub_cfg, &slug).await?;

            let client_failed = client_steps.iter().any(|(_, ok, _)| !ok);
            let gs_failed = gs_steps.iter().any(|(_, ok, _)| !ok);
            let ok_overall = !client_failed && !gs_failed;
            let message = if ok_overall {
                format!("Client '{}' fully uninstalled (unit + drop-in + data + game server)", slug)
            } else {
                format!(
                    "Client '{}' uninstall completed with errors — see steps",
                    slug
                )
            };

            report_progress(
                http,
                base_url,
                action_id,
                3,
                "done",
                &message,
                Some(100),
            )
            .await;

            let to_json = |steps: Vec<(String, bool, String)>| -> Vec<serde_json::Value> {
                steps
                    .into_iter()
                    .map(|(step, ok, msg)| json!({ "step": step, "ok": ok, "message": msg }))
                    .collect()
            };
            let data = json!({
                "slug": slug,
                "client_steps": to_json(client_steps),
                "game_server_steps": to_json(gs_steps),
                "all_ok": ok_overall,
            });

            if ok_overall {
                Ok((message, Some(data)))
            } else {
                // Bubble up a detailed error so the UI shows the red failure
                // banner and admins see the step log in the progress panel.
                let detail = serde_json::to_string(&data).unwrap_or_default();
                anyhow::bail!("{}: {}", message, detail)
            }
        }
        HubAction::StartClient { slug } => {
            let unit = client_manager::unit_name(hub_cfg, &slug);
            client_manager::systemctl_action(&unit, "start").await?;
            Ok((format!("Started {}", unit), None))
        }
        HubAction::StopClient { slug } => {
            let unit = client_manager::unit_name(hub_cfg, &slug);
            client_manager::systemctl_action(&unit, "stop").await?;
            Ok((format!("Stopped {}", unit), None))
        }
        HubAction::RestartClient { slug } => {
            let unit = client_manager::unit_name(hub_cfg, &slug);
            client_manager::systemctl_action(&unit, "restart").await?;
            Ok((format!("Restarted {}", unit), None))
        }
        HubAction::InstallGameServer { slug, params } => {
            let path = game_server_manager::install_game_server(hub_cfg, &slug, &params).await?;
            Ok((
                format!("Game server installed at {}", path.display()),
                Some(json!({ "slug": slug, "install_path": path })),
            ))
        }
        HubAction::RemoveGameServer { slug } => {
            let steps = game_server_manager::remove_game_server(hub_cfg, &slug).await?;
            let failed = steps.iter().any(|(_, ok, _)| !ok);
            let data = json!({
                "slug": slug,
                "steps": steps.into_iter().map(|(step, ok, msg)| json!({
                    "step": step, "ok": ok, "message": msg,
                })).collect::<Vec<_>>(),
                "all_ok": !failed,
            });
            if failed {
                let detail = serde_json::to_string(&data).unwrap_or_default();
                anyhow::bail!("Game server {} removal had errors: {}", slug, detail)
            } else {
                Ok((format!("Game server {} removed", slug), Some(data)))
            }
        }
        HubAction::UpdateClient { slug } => {
            // Placeholder: a future iteration will pull the binary into the
            // per-client dir and restart the unit.
            Ok((format!("Update for client {} queued (stub)", slug), None))
        }
        HubAction::GetClientLogs { slug, tail_lines } => {
            let unit = client_manager::unit_name(hub_cfg, &slug);
            let out = tokio::process::Command::new("journalctl")
                .args([
                    "-u",
                    &unit,
                    "-n",
                    &tail_lines.to_string(),
                    "--no-pager",
                    "--output=short-iso",
                ])
                .output()
                .await?;
            let logs = String::from_utf8_lossy(&out.stdout).to_string();
            Ok((format!("{} log lines for {}", tail_lines, unit), Some(json!({ "logs": logs }))))
        }
        HubAction::GetHubVersion => Ok((
            "Hub version".to_string(),
            Some(json!({
                "version": env!("CARGO_PKG_VERSION"),
                "build_hash": option_env!("R3_BUILD_HASH").unwrap_or("unknown"),
            })),
        )),
        HubAction::Restart => {
            // Re-exec ourselves: simplest way is exit and let systemd restart us.
            tokio::spawn(async {
                tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                std::process::exit(0);
            });
            Ok(("Hub will restart momentarily".to_string(), None))
        }
        HubAction::ForceUpdate { update_url, channel } => {
            // Resolve effective URL + channel. Fall back to whatever the hub
            // itself is configured with so admins can trigger a manual update
            // without having to remember to send both params.
            let effective_url = update_url
                .clone()
                .unwrap_or_else(|| "https://r3.pugbot.net/api/updates".to_string());
            let effective_channel = channel.clone().unwrap_or_else(|| "beta".to_string());

            let current_build = option_env!("R3_BUILD_HASH").unwrap_or("unknown").to_string();

            let update = match crate::update::check_for_update(
                &effective_url,
                &effective_channel,
                &current_build,
            )
            .await
            {
                Ok(Some(u)) => u,
                Ok(None) => {
                    return Ok((
                        format!("Hub already up to date ({})", current_build),
                        Some(json!({
                            "response_type": "AlreadyUpToDate",
                            "current_build": current_build,
                        })),
                    ));
                }
                Err(e) => {
                    return Ok((
                        format!("Hub update check failed: {}", e),
                        Some(json!({
                            "response_type": "Error",
                            "message": e.to_string(),
                        })),
                    ));
                }
            };

            let target_build = update.manifest.build_hash.clone();
            let target_version = update.manifest.version.clone();
            let download_size = update.platform.size;
            let binary_url = update.platform.url.clone();
            let binary_sha = update.platform.sha256.clone();

            // Apply + restart asynchronously so we can return a response
            // to the master before the hub process is re-exec'd.
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(2)).await;
                match crate::update::download_and_verify(&binary_url, &binary_sha).await {
                    Ok(temp_path) => match crate::update::apply_update(&temp_path) {
                        Ok(_) => {
                            tracing::info!("Hub force-update applied, restarting...");
                            crate::update::restart();
                        }
                        Err(e) => {
                            tracing::error!(error = %e, "Hub force-update: apply_update failed");
                            let _ = std::fs::remove_file(&temp_path);
                        }
                    },
                    Err(e) => {
                        tracing::error!(error = %e, "Hub force-update: download failed");
                    }
                }
            });

            Ok((
                format!("Hub update triggered: {} -> {}", current_build, target_build),
                Some(json!({
                    "response_type": "UpdateTriggered",
                    "current_build": current_build,
                    "target_build": target_build,
                    "target_version": target_version,
                    "download_size": download_size,
                })),
            ))
        }
        HubAction::SelfUninstall { remove_gameserver, update_url } => {
            // 1. Tear down every managed r3-client@<slug>.service first.
            let clients = client_manager::list_client_statuses(hub_cfg).await;
            let mut removed = Vec::new();
            let mut failed: Vec<(String, String)> = Vec::new();
            for c in &clients {
                match client_manager::uninstall_client(hub_cfg, &c.slug, true).await {
                    Ok(_) => removed.push(c.slug.clone()),
                    Err(e) => failed.push((c.slug.clone(), e.to_string())),
                }
                // Best-effort game-server teardown per client during a full
                // host uninstall. Errors are non-fatal here since the host
                // is going away anyway.
                if remove_gameserver {
                    if let Err(e) = game_server_manager::remove_game_server(hub_cfg, &c.slug).await
                    {
                        tracing::warn!(slug = %c.slug, error = %e,
                            "Game server cleanup failed during self-uninstall");
                    }
                }
            }
            for (slug, err) in &failed {
                tracing::warn!(%slug, %err, "Failed to uninstall sub-client during hub self-uninstall");
            }

            // 2. Spawn the host-level uninstaller as a transient unit so it
            //    survives our own systemd unit being stopped, then exit.
            let effective_url = update_url
                .unwrap_or_else(|| "https://r3.pugbot.net/api/updates".to_string());
            let spawn_result =
                crate::core::self_uninstall::trigger(&effective_url, true, remove_gameserver);

            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                std::process::exit(0);
            });

            let message = match spawn_result {
                Ok(m) => format!(
                    "Hub self-uninstall dispatched. Removed {} sub-client(s){}. {}",
                    removed.len(),
                    if failed.is_empty() {
                        String::new()
                    } else {
                        format!(" (failed: {})", failed.len())
                    },
                    m
                ),
                Err(e) => format!(
                    "Hub will exit but self-uninstall dispatch failed: {}",
                    e
                ),
            };
            Ok((
                message,
                Some(json!({
                    "response_type": "SelfUninstallDispatched",
                    "removed_clients": removed,
                    "failed_clients": failed.iter().map(|(s, _)| s).collect::<Vec<_>>(),
                })),
            ))
        }
    }
}
