//! Dispatch table mapping `HubAction` values to concrete operations.

use serde_json::json;

use crate::config::HubSection;
use crate::sync::protocol::{HubAction, MintClientCertRequest, MintClientCertResponse};

use super::{client_manager, game_server_manager};

/// Build an `r3.toml` for a hub-managed client. Mirrors the layout the
/// standalone installer writes in `generate_client_config`, minus any
/// fields that are configured later by the master web UI wizard.
fn render_client_toml(
    slug: &str,
    server_name: &str,
    master_sync_url: &str,
    client_dir: &std::path::Path,
) -> String {
    let certs_dir = client_dir.join("certs");
    format!(
        r#"# Rusty Rules Referee — Hub-managed client ({slug})
# Generated by hub on client install. Managed by master at {master}

[referee]
bot_name = "{server_name}"
bot_prefix = "^2R3:^3"
database = "sqlite://r3.db"
logfile = "r3.log"
log_level = "info"

[server]
public_ip = "0.0.0.0"
port = 0
rcon_password = ""
game_log = ""
delay = 0.33

[web]
enabled = false
bind_address = "0.0.0.0"
port = 2727
jwt_secret = ""

[update]
enabled = false
url = "https://r3.pugbot.net/api/updates"
channel = "beta"
check_interval = 3600
auto_restart = true

[client]
master_url = "{master}"
server_name = "{server_name}"
tls_cert = "{cert}"
tls_key = "{key}"
ca_cert = "{ca}"
sync_interval = 30
heartbeat_interval = 15

[[plugins]]
name = "admin"
enabled = true

[[plugins]]
name = "poweradminurt"
enabled = true

[[plugins]]
name = "censor"
enabled = true

[[plugins]]
name = "welcome"
enabled = true

[[plugins]]
name = "stats"
enabled = true
"#,
        slug = slug,
        server_name = server_name,
        master = master_sync_url,
        cert = certs_dir.join("client.crt").display(),
        key = certs_dir.join("client.key").display(),
        ca = certs_dir.join("ca.crt").display(),
    )
}

/// Execute a single hub action. Returns `(message, optional structured data)`.
pub async fn execute(
    http: &reqwest::Client,
    base_url: &str,
    hub_id: i64,
    hub_cfg: &HubSection,
    action: HubAction,
) -> anyhow::Result<(String, Option<serde_json::Value>)> {
    match action {
        HubAction::InstallClient {
            slug,
            server_name,
            game_server,
            register_systemd: _,
        } => {
            // 1) Mint a client certificate + register the GameServer row
            //    on the master via the hub's mTLS-authenticated endpoint.
            let (address, port) = if let Some(params) = &game_server {
                (params.public_ip.clone(), params.port)
            } else {
                (String::new(), 0u16)
            };
            let mint_req = MintClientCertRequest {
                hub_id,
                slug: slug.clone(),
                server_name: server_name.clone(),
                address,
                port,
            };
            let resp = http
                .post(format!("{}/internal/hub/mint-client-cert", base_url))
                .json(&mint_req)
                .send()
                .await
                .map_err(|e| anyhow::anyhow!("mint-client-cert request: {}", e))?;
            if !resp.status().is_success() {
                let status = resp.status();
                let body = resp.text().await.unwrap_or_default();
                anyhow::bail!("mint-client-cert returned {}: {}", status, body);
            }
            let mint: MintClientCertResponse = resp
                .json()
                .await
                .map_err(|e| anyhow::anyhow!("parse mint-client-cert response: {}", e))?;

            // 2) Render r3.toml and write certs + install systemd drop-in.
            let dir = client_manager::client_dir(hub_cfg, &slug);
            let r3_toml = render_client_toml(&slug, &server_name, &mint.master_sync_url, &dir);
            client_manager::install_client(
                hub_cfg,
                &slug,
                &r3_toml,
                &mint.ca_cert,
                &mint.client_cert,
                &mint.client_key,
            )
            .await?;

            // 3) Optionally drop game-server files alongside the client.
            let mut data = json!({
                "slug": slug,
                "server_id": mint.server_id,
                "client_dir": dir.display().to_string(),
            });
            if let Some(params) = game_server {
                let path =
                    game_server_manager::install_game_server(hub_cfg, &slug, &params).await?;
                data["game_server_path"] = json!(path.display().to_string());
            }

            Ok((
                format!(
                    "Client '{}' installed (server_id={}, dir={})",
                    slug,
                    mint.server_id,
                    dir.display()
                ),
                Some(data),
            ))
        }
        HubAction::UninstallClient { slug, remove_data } => {
            client_manager::uninstall_client(hub_cfg, &slug, remove_data).await?;
            Ok((format!("Client {} uninstalled", slug), None))
        }
        HubAction::StartClient { slug } => {
            let unit = client_manager::unit_name(hub_cfg, &slug);
            client_manager::systemctl_action(&unit, "start").await?;
            Ok((format!("Started {}", unit), None))
        }
        HubAction::StopClient { slug } => {
            let unit = client_manager::unit_name(hub_cfg, &slug);
            client_manager::systemctl_action(&unit, "stop").await?;
            Ok((format!("Stopped {}", unit), None))
        }
        HubAction::RestartClient { slug } => {
            let unit = client_manager::unit_name(hub_cfg, &slug);
            client_manager::systemctl_action(&unit, "restart").await?;
            Ok((format!("Restarted {}", unit), None))
        }
        HubAction::InstallGameServer { slug, params } => {
            let path = game_server_manager::install_game_server(hub_cfg, &slug, &params).await?;
            Ok((
                format!("Game server installed at {}", path.display()),
                Some(json!({ "slug": slug, "install_path": path })),
            ))
        }
        HubAction::RemoveGameServer { slug } => {
            game_server_manager::remove_game_server(hub_cfg, &slug).await?;
            Ok((format!("Game server {} removed", slug), None))
        }
        HubAction::UpdateClient { slug } => {
            // Placeholder: a future iteration will pull the binary into the
            // per-client dir and restart the unit.
            Ok((format!("Update for client {} queued (stub)", slug), None))
        }
        HubAction::GetClientLogs { slug, tail_lines } => {
            let unit = client_manager::unit_name(hub_cfg, &slug);
            let out = tokio::process::Command::new("journalctl")
                .args([
                    "-u",
                    &unit,
                    "-n",
                    &tail_lines.to_string(),
                    "--no-pager",
                    "--output=short-iso",
                ])
                .output()
                .await?;
            let logs = String::from_utf8_lossy(&out.stdout).to_string();
            Ok((format!("{} log lines for {}", tail_lines, unit), Some(json!({ "logs": logs }))))
        }
        HubAction::GetHubVersion => Ok((
            "Hub version".to_string(),
            Some(json!({
                "version": env!("CARGO_PKG_VERSION"),
                "build_hash": option_env!("R3_BUILD_HASH").unwrap_or("unknown"),
            })),
        )),
        HubAction::Restart => {
            // Re-exec ourselves: simplest way is exit and let systemd restart us.
            tokio::spawn(async {
                tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                std::process::exit(0);
            });
            Ok(("Hub will restart momentarily".to_string(), None))
        }
        HubAction::ForceUpdate { update_url, channel } => {
            // Resolve effective URL + channel. Fall back to whatever the hub
            // itself is configured with so admins can trigger a manual update
            // without having to remember to send both params.
            let effective_url = update_url
                .clone()
                .unwrap_or_else(|| "https://r3.pugbot.net/api/updates".to_string());
            let effective_channel = channel.clone().unwrap_or_else(|| "beta".to_string());

            let current_build = option_env!("R3_BUILD_HASH").unwrap_or("unknown").to_string();

            let update = match crate::update::check_for_update(
                &effective_url,
                &effective_channel,
                &current_build,
            )
            .await
            {
                Ok(Some(u)) => u,
                Ok(None) => {
                    return Ok((
                        format!("Hub already up to date ({})", current_build),
                        Some(json!({
                            "response_type": "AlreadyUpToDate",
                            "current_build": current_build,
                        })),
                    ));
                }
                Err(e) => {
                    return Ok((
                        format!("Hub update check failed: {}", e),
                        Some(json!({
                            "response_type": "Error",
                            "message": e.to_string(),
                        })),
                    ));
                }
            };

            let target_build = update.manifest.build_hash.clone();
            let target_version = update.manifest.version.clone();
            let download_size = update.platform.size;
            let binary_url = update.platform.url.clone();
            let binary_sha = update.platform.sha256.clone();

            // Apply + restart asynchronously so we can return a response
            // to the master before the hub process is re-exec'd.
            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_secs(2)).await;
                match crate::update::download_and_verify(&binary_url, &binary_sha).await {
                    Ok(temp_path) => match crate::update::apply_update(&temp_path) {
                        Ok(_) => {
                            tracing::info!("Hub force-update applied, restarting...");
                            crate::update::restart();
                        }
                        Err(e) => {
                            tracing::error!(error = %e, "Hub force-update: apply_update failed");
                            let _ = std::fs::remove_file(&temp_path);
                        }
                    },
                    Err(e) => {
                        tracing::error!(error = %e, "Hub force-update: download failed");
                    }
                }
            });

            Ok((
                format!("Hub update triggered: {} -> {}", current_build, target_build),
                Some(json!({
                    "response_type": "UpdateTriggered",
                    "current_build": current_build,
                    "target_build": target_build,
                    "target_version": target_version,
                    "download_size": download_size,
                })),
            ))
        }
        HubAction::SelfUninstall { remove_gameserver, update_url } => {
            // 1. Tear down every managed r3-client@<slug>.service first.
            let clients = client_manager::list_client_statuses(hub_cfg).await;
            let mut removed = Vec::new();
            let mut failed: Vec<(String, String)> = Vec::new();
            for c in &clients {
                match client_manager::uninstall_client(hub_cfg, &c.slug, true).await {
                    Ok(_) => removed.push(c.slug.clone()),
                    Err(e) => failed.push((c.slug.clone(), e.to_string())),
                }
            }
            for (slug, err) in &failed {
                tracing::warn!(%slug, %err, "Failed to uninstall sub-client during hub self-uninstall");
            }

            // 2. Spawn the host-level uninstaller as a transient unit so it
            //    survives our own systemd unit being stopped, then exit.
            let effective_url = update_url
                .unwrap_or_else(|| "https://r3.pugbot.net/api/updates".to_string());
            let spawn_result =
                crate::core::self_uninstall::trigger(&effective_url, true, remove_gameserver);

            tokio::spawn(async move {
                tokio::time::sleep(std::time::Duration::from_millis(500)).await;
                std::process::exit(0);
            });

            let message = match spawn_result {
                Ok(m) => format!(
                    "Hub self-uninstall dispatched. Removed {} sub-client(s){}. {}",
                    removed.len(),
                    if failed.is_empty() {
                        String::new()
                    } else {
                        format!(" (failed: {})", failed.len())
                    },
                    m
                ),
                Err(e) => format!(
                    "Hub will exit but self-uninstall dispatch failed: {}",
                    e
                ),
            };
            Ok((
                message,
                Some(json!({
                    "response_type": "SelfUninstallDispatched",
                    "removed_clients": removed,
                    "failed_clients": failed.iter().map(|(s, _)| s).collect::<Vec<_>>(),
                })),
            ))
        }
    }
}
